<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Access denied.' => 'Akses ditolak.',
	'Add' => 'Tambah',
	'Add child' => 'Tambah turunan',
	'Add {type}' => 'Tambah {type}',
	'Ancestors' => 'Induk',
	'Are you sure you want to delete this item?' => 'Anda yakin mau menghapus item ini?',
	'Assign' => 'Ijinkan',
	'Assign permission' => 'Ijinkan akses',
	'Assigned items' => 'Akses yg diijinkan',
	'Assignments' => 'Pengaturan Akses',
	'Business rule' => 'Aturan bisnis',
	'Cancel' => 'Batal',
	'Create' => 'Buat',
	'Delete' => 'Hapus',
	'Data' => 'Data',
	'Descendants' => 'Turunan',
	'Description' => 'Keterangan',
	'Edit' => 'Ubah',
	'Invalid request.' => 'Permintaan tidak dapat diproses.',
	'Item does not exist.' => 'Item tidak ditemukan.',
	'Items' => 'Item',
	'Items assigned to this user' => 'Akses yang diberikan ke pengguna ini',
	'New {type}' => 'Tambah {type}',
	'No assignments found.' => 'Tidak ada penugasan.',
	'No {type} found.' => '{type} tidak ditemukan.',
	'Page not found.' => 'Halaman tidak ditemukan.',
	'Permissions' => 'Hak Akses',
	'Permissions granted by this item' => 'Akses yang diberikan untuk item ini',
	'Permissions that inherit this item' => 'Akses yang mewarisi item ini',
	'Remove' => 'Hapus',
	'Revoke' => 'Cabut',
	'Save' => 'Simpan',
	'Select item' => 'Pilih item',
	'System name' => 'Nama di sistem',
	'System name cannot be changed after creation.' => 'Nama di sistem tidak boleh diubah setelah disimpan',
	'This item does not have any ancestors.' => 'Item ini tidak memiliki induk',
	'This item does not have any descendants.' => 'Item ini tidak memiliki turunan',
	'This user does not have any assignments.' => 'Pengguna ini tidak memiliki penugasan',
	'Type' => 'Jenis',
	'User' => 'Pengguna',
	'View' => 'Lihat',
	'operation|operations' => 'Action',
	'role|roles' => 'Peran',
	'task|tasks' => 'Tugas',
);
